#!/usr/bin/env bash

set -o errexit

ERR='\033[0;31m'
NC='\033[0m'

if [ -z "$1" ]; then
  echo -e "${ERR}error: no file specified${NC}"
  echo "usage: $0 [file-path]"
  exit 1
fi

if [ ! -f "$1" ]; then
  echo -e "${ERR}error: file '$1' not found${NC}"
  exit 1
fi

IMAGE_PATH=$(realpath $1)
gsettings set org.gnome.desktop.background picture-uri      "file://${IMAGE_PATH}"
gsettings set org.gnome.desktop.background picture-uri-dark "file://${IMAGE_PATH}"
